INSERT INTO unidade_medida (nome, sigla) VALUES
('Unidade', 'un'),
('Quilograma', 'kg'),
('Grama', 'g'),
('Litro', 'L'),
('Mililitro', 'ml'),
('Metro', 'm'),
('Centímetro', 'cm'),
('Milímetro', 'mm'),
('Caixa', 'cx'),
('Pacote', 'pct'),
('Galão', 'gal'),
('Par', 'par'),
('Dúzia', 'dz'),
('Saco', 'sc');