"""create tables from models

Revision ID: fc8112dd25bd
Revises: 0972b7d1d456
Create Date: 2025-09-25 21:50:02.560432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8112dd25bd'
down_revision: Union[str, Sequence[str], None] = '0972b7d1d456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('categoria_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('categoria_id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('configuracoes_comercio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unidade_padrao', sa.String(length=20), nullable=False),
    sa.Column('nivel_alerta_minimo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moeda_padrao', sa.CHAR(length=3), nullable=False),
    sa.Column('linguagem', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores',
    sa.Column('fornecedor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('fornecedor_id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('unidade_medidas',
    sa.Column('unimed_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('unimed_id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('comercios',
    sa.Column('comercio_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proprietario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('configuracao_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['configuracao_id'], ['configuracoes_comercio.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proprietario_id'], ['usuarios.usuario_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('comercio_id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tabela_nome', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('operacao', sa.String(length=10), nullable=False),
    sa.Column('alterado_por', sa.Integer(), nullable=True),
    sa.Column('alterado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('antigo_dado', sa.JSON(), nullable=True),
    sa.Column('novo_dado', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['alterado_por'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('produtos',
    sa.Column('produto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('unidade_medida_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.categoria_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.fornecedor_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unidade_medida_id'], ['unidade_medidas.unimed_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('produto_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('comercios_usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comercio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comercio_id'], ['comercios.comercio_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'comercio_id', 'usuario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comercios_usuarios')
    op.drop_table('produtos')
    op.drop_table('logs')
    op.drop_table('comercios')
    op.drop_table('usuarios')
    op.drop_table('unidade_medidas')
    op.drop_table('fornecedores')
    op.drop_table('configuracoes_comercio')
    op.drop_table('categorias')
    # ### end Alembic commands ###
