CREATE TABLE IF NOT EXISTS produtos (
    produto_id SERIAL PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nome VARCHAR(150) NOT NULL,
    preco NUMERIC(10, 2) NOT NULL,
    quantidade_estoque INT NOT NULL DEFAULT 0,

    unimed_id INT NOT NULL REFRENCES unidade_medidas(unimed_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    categoria_id INT NOT NULL REFRENCES categorias(categoria_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    fornecedor_id INT NOT NULL REFRENCES fornecedores(fornecedor_id) ON DELETE RESTRICT ON UPDATE CASCADE,

	criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    ENABLE ROW LEVEL SECURITY
);

