"""rename column tag to tags in produtos

Revision ID: 1975711c13f0
Revises: manual_add_tag_to_produtos
Create Date: 2025-10-17 13:28:16.091556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1975711c13f0'
down_revision: Union[str, Sequence[str], None] = 'manual_add_tag_to_produtos'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('tags', sa.String(length=100), nullable=True))
    op.drop_column('produtos', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('tag', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('produtos', 'tags')
    # ### end Alembic commands ###
