"""adiciona uq em nome e proprietario_id em comercios

Revision ID: 34cc04bef586
Revises: fe9ad05bbe3f
Create Date: 2025-11-25 13:54:06.536373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cc04bef586'
down_revision: Union[str, Sequence[str], None] = 'fe9ad05bbe3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comercios_nome_key'), 'comercios', type_='unique')
    op.create_unique_constraint('uq_nome_proprietario_id', 'comercios', ['nome', 'proprietario_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_nome_proprietario_id', 'comercios', type_='unique')
    op.create_unique_constraint(op.f('comercios_nome_key'), 'comercios', ['nome'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
