"""atualiza movs e outras coisas

Revision ID: a09b6c11b8c3
Revises: 2287e3385f6f
Create Date: 2025-11-15 22:27:57.607499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09b6c11b8c3'
down_revision: Union[str, Sequence[str], None] = '2287e3385f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        'logs',
        'record_id',
        existing_type=sa.TEXT(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="record_id::integer"
    )
    op.add_column('movimentacoes', sa.Column('estado', sa.String(length=7), nullable=False))
    op.add_column('movimentacoes', sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('fk_produtos_fornecedor_id'), 'produtos', type_='foreignkey')
    op.drop_constraint(op.f('fk_produtos_categoria_id'), 'produtos', type_='foreignkey')
    op.drop_constraint(op.f('produtos_categoria_id_fkey'), 'produtos', type_='foreignkey')
    op.drop_constraint(op.f('produtos_fornecedor_id_fkey'), 'produtos', type_='foreignkey')
    op.create_foreign_key(None, 'produtos', 'fornecedores', ['fornecedor_id'], ['fornecedor_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'produtos', 'categorias', ['categoria_id'], ['categoria_id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.create_foreign_key(op.f('produtos_fornecedor_id_fkey'), 'produtos', 'fornecedores', ['fornecedor_id'], ['fornecedor_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('produtos_categoria_id_fkey'), 'produtos', 'categorias', ['categoria_id'], ['categoria_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_produtos_categoria_id'), 'produtos', 'categorias', ['categoria_id'], ['categoria_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_produtos_fornecedor_id'), 'produtos', 'fornecedores', ['fornecedor_id'], ['fornecedor_id'], ondelete='SET NULL')
    op.drop_column('movimentacoes', 'fechado_em')
    op.drop_column('movimentacoes', 'estado')
    op.alter_column('logs', 'record_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
