"""record_id para texto 2 - text

Revision ID: e032efe164eb
Revises: a09b6c11b8c3
Create Date: 2025-11-15 23:14:06.192379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e032efe164eb'
down_revision: Union[str, Sequence[str], None] = 'a09b6c11b8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    'logs',
    'record_id',
    existing_type=sa.Integer(),
    type_=sa.Text(),
    postgresql_using='record_id::text'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    #     # tudo é um erro. o mundo é ma ilusão. ele está fvindo
    # corra
    # fuja
    # e
    # s
    # t
    # á
    # 
    # t
    # as´ldkslkdnalkda
    # demaise

    op.alter_column(
    'logs',
    'record_id',
    existing_type=sa.Text(),
    type_=sa.Integer(),
    postgresql_using='record_id::integer'
    )
    # ### end Alembic commands ###

