"""move movimentacoes.desconto_percentual to carrinho_item

Revision ID: e42402e034ca
Revises: a0c82a12bab9
Create Date: 2025-11-14 14:37:52.691740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42402e034ca'
down_revision: Union[str, Sequence[str], None] = 'a0c82a12bab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrinho_itens', sa.Column('desconto_percentual', sa.Numeric(precision=6, scale=4), nullable=True))
    op.drop_index(op.f('ix_carrinho_itens_carrinho_id'), table_name='carrinho_itens')
    op.add_column('movimentacoes', sa.Column('link', sa.String(length=16), nullable=False))
    op.alter_column('movimentacoes', 'tipo',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=7),
               existing_nullable=False)
    op.alter_column('movimentacoes', 'carrinho_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_movimentacoes_tipo'), table_name='movimentacoes')
    op.create_unique_constraint(None, 'movimentacoes', ['link'])
    op.drop_constraint(op.f('movimentacoes_carrinho_id_fkey'), 'movimentacoes', type_='foreignkey')
    op.create_foreign_key(None, 'movimentacoes', 'carrinhos', ['carrinho_id'], ['carrinho_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('movimentacoes', 'desconto_percentual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentacoes', sa.Column('desconto_percentual', sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'movimentacoes', type_='foreignkey')
    op.create_foreign_key(op.f('movimentacoes_carrinho_id_fkey'), 'movimentacoes', 'carrinhos', ['carrinho_id'], ['carrinho_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(None, 'movimentacoes', type_='unique')
    op.create_index(op.f('ix_movimentacoes_tipo'), 'movimentacoes', ['tipo'], unique=False)
    op.alter_column('movimentacoes', 'carrinho_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movimentacoes', 'tipo',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_column('movimentacoes', 'link')
    op.drop_constraint(None, 'fornecedores', type_='unique')
    op.create_index(op.f('ix_carrinho_itens_carrinho_id'), 'carrinho_itens', ['carrinho_id'], unique=False)
    op.drop_column('carrinho_itens', 'desconto_percentual')
    # ### end Alembic commands ###
