"""Atualiza banco para refletir modelo atual do back

Revision ID: ea9d365011aa
Revises: 6abd541b361f
Create Date: 2025-10-29 19:21:12.594996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9d365011aa'
down_revision: Union[str, Sequence[str], None] = '6abd541b361f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contadores_locais', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_contadores_locais_scope_comercio'), table_name='contadores_locais')
    op.drop_index(op.f('ix_enderecos_cep'), table_name='enderecos')
    op.drop_index(op.f('ix_fornecedores_endereco_id'), table_name='fornecedores')
    op.drop_constraint(op.f('produtos_comercio_codigo_key'), 'produtos', type_='unique')
    op.create_unique_constraint('produtos_comercio_key', 'produtos', ['comercio_id', 'codigo'])
    op.drop_index(op.f('ux_unimed_comercio_sigla'), table_name='unidade_medidas', postgresql_where='(comercio_id IS NOT NULL)')
    op.drop_index(op.f('ux_unimed_sigla_global'), table_name='unidade_medidas', postgresql_where='(comercio_id IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ux_unimed_sigla_global'), 'unidade_medidas', [sa.literal_column('lower(sigla::text)')], unique=True, postgresql_where='(comercio_id IS NULL)')
    op.create_index(op.f('ux_unimed_comercio_sigla'), 'unidade_medidas', ['comercio_id', sa.literal_column('lower(sigla::text)')], unique=True, postgresql_where='(comercio_id IS NOT NULL)')
    op.drop_constraint('produtos_comercio_key', 'produtos', type_='unique')
    op.create_unique_constraint(op.f('produtos_comercio_codigo_key'), 'produtos', ['comercio_id', 'codigo'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_fornecedores_endereco_id'), 'fornecedores', ['endereco_id'], unique=False)
    op.create_index(op.f('ix_enderecos_cep'), 'enderecos', ['cep'], unique=False)
    op.create_index(op.f('ix_contadores_locais_scope_comercio'), 'contadores_locais', ['scope', 'comercio_id'], unique=False)
    op.drop_column('contadores_locais', 'updated_at')
    # ### end Alembic commands ###
